[package]
name = "hello_ggez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.0-rc0"
nalgebra = "0.16.0"
rand = "0.8"
image = "0.23.8"
lazy_static = "1.4"
winapi = "0.3.9"